[package]
name = "k4svm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k4s = { path = "../k4s" }
bitflags = "2.0.2"
zerocopy = { version = "0.6.1", features = ["alloc", "simd"] }
nom = "7.1.3"